### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ChefMC** [MegavexNetwork/AdvancedSlimePufferfish#2]
![image](https://github.com/MegavexNetwork/AdvancedSlimePufferfish/assets/3519015/7a80798d-5fb5-463a-a86f-57f494afb70f)

**Comment by vytskalt** [comment]
you need to run `./gradlew applyPatches` first before `./gradlew createReobfBundlerJar`

**Comment by ChefMC** [comment]
Are you keeping up to date AdvancedSlimePaper upstream?

**Comment by ChefMC** [comment]
Because seems like it updating multiple times every day and may contain very important updates

**Comment by vytskalt** [comment]
> Are you keeping up to date AdvancedSlimePaper upstream?

Yes

> Because seems like it updating multiple times every day and may contain very important updates

The updates are only just updating to the latest version of paper, last actual change was 2 months ago

**Comment by ChefMC** [comment]
What is this?

![image](https://github.com/MegavexNetwork/AdvancedSlimePufferfish/assets/3519015/ad0e03a3-32f7-4ddf-9364-c32d26dd122c)

**Comment by ChefMC** [comment]
I want AdvancedSlime on Pufferfish, but also want this updates

**Comment by vytskalt** [comment]
> What is this?
> 
> ![image](https://user-images.githubusercontent.com/3519015/262444868-ad0e03a3-32f7-4ddf-9364-c32d26dd122c.png)

Those are experimental automatic updates which update to latest paper version. If you go to the [upstream repository](https://github.com/InfernalSuite/AdvancedSlimePaper) you can see that the last slime manager related change was 2 months ago.

**Comment by ChefMC** [comment]
Got it.
How I can apply those changes to AdvancedSlimePufferfish?

**Comment by vytskalt** [comment]
> Got it. How I can apply those changes to AdvancedSlimePufferfish?

What changes are you talking about? This project is already using the latest version of the slime manager and pufferfish. To build it, run `./gradlew applyPatches` and then `./gradlew createReobfBundlerJar`. If everything went well the jar should be in the `build/libs` directory

**Comment by ChefMC** [comment]
These 2 commands enough to apply
> experimental automatic updates which update to latest paper version

?

**Comment by ChefMC** [comment]
It's too slow O_O

![image](https://github.com/MegavexNetwork/AdvancedSlimePufferfish/assets/3519015/4d684b50-d1cf-4fa5-8705-b5e82fd385b8)

2h 08min

**Comment by vytskalt** [comment]
> It's too slow O_O
> 
> ![image](https://user-images.githubusercontent.com/3519015/262468013-4d684b50-d1cf-4fa5-8705-b5e82fd385b8.png)
> 
> 1h 36min

Yeah that's a known issue when building on Windows. The workaround is to use WSL

**Comment by ChefMC** [comment]
It's WSL

![image](https://github.com/MegavexNetwork/AdvancedSlimePufferfish/assets/3519015/3216579c-f9b1-4225-b391-0a1ee38a1277)

**Comment by vytskalt** [comment]
> It's WSL
> 
> ![image](https://user-images.githubusercontent.com/3519015/262477078-3216579c-f9b1-4225-b391-0a1ee38a1277.png)

I think you also need to move it to a linux filesystem, so in `/home/...` instead of `/mnt/d/...`

**Comment by ChefMC** [comment]
Thank you 🙏, will test it on next building

**Comment by vytskalt** [comment]
> These 2 commands enough to apply
> 
> > experimental automatic updates which update to latest paper version
> 
> ?

No, but you can do it by going into the `gradle.properties` file and replacing `pufferfishRef` with the latest commit hash of the [Pufferfish](https://github.com/pufferfish-gg/Pufferfish) repository.

**Comment by ChefMC** [comment]
After `./gradlew createReobfPaperclipJar`:

![image](https://github.com/MegavexNetwork/AdvancedSlimePufferfish/assets/3519015/9843f1c1-d051-4ed7-9bf1-a6a1eb616090)

**Comment by ChefMC** [comment]
Also getting spam of this in server console:

![image](https://github.com/MegavexNetwork/AdvancedSlimePufferfish/assets/3519015/6343ce17-4d72-4788-90bf-c7570f7060fd)

I think I somehow should build also plugin for Pufferfish. In AdvancedSlime**Paper** all is fine

**Comment by vytskalt** [comment]
> Also getting spam of this in server console:
> 
> ![image](https://user-images.githubusercontent.com/3519015/262505847-6343ce17-4d72-4788-90bf-c7570f7060fd.png)
> 
> I think I somehow should build also plugin for Pufferfish. In AdvancedSlime**Paper** all is fine

You should be able to use the paper plugin fine, there havent been any changes in it

**Comment by ChefMC** [comment]
But what the problem of those messages? 
Also world doesn't actually converting to .slime on this build (on original Paper version all is fine)

And how to solve problem below?

> After `./gradlew createReobfPaperclipJar`:
> 
> ![image](https://user-images.githubusercontent.com/3519015/262496304-9843f1c1-d051-4ed7-9bf1-a6a1eb616090.png)

**Comment by vytskalt** [comment]
> ./gradlew createReobfPaperclipJar

I don't know what the errors mean, but looks like they can be ignored: https://discord.com/channels/741733106930810950/741734887538688092/1140400078570410125

Not sure about the build error, it works fine for me. You can try resetting the repository and redoing the `./gradlew applyPatches`

And what do you mean by "world doesn't actually converting to .slime on this build"?
