### ISSUE TITLE
Stop server error

### ISSUE THREAD

**Issue by ChefMC** [MegavexNetwork/AdvancedSlimePufferfish#3]
**Describe the issue**
https://just-paste.it/4xRdgx5Slr

**Spigot version**
1.20.2

**Plugin version**
2.10.0

**How to reproduce**
1. Start server and wait full initialization ("Done in" message and some seconds)
2. Type `/save-all`
3. Type `/stop`

**Comment by ChefMC** [comment]
Downloaded from "Infernal Suite" Discord in this message in `#aspuff-builds` channel (Oct 31 message):
https://discord.com/channels/741733106930810950/1168669589270446154/1168690364517974088

**Comment by vytskalt** [comment]
I just updated Pufferfish and ASP to the latest versions, can you check if this was fixed?
